/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Data.DataUsers;
import Data.SG;
import ImagePathList.Image;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author bruce
 */
public class Biblioteca extends javax.swing.JFrame {

    /**
     * Creates new form Biblioteca
     */
    private File fichero;
    public Biblioteca() {
        initComponents();
        lblUser.setText(Data.SG.user);
        initialCBOImage();
    }
    
    public void initialCBOImage(){
        int size= Data.SG.lista_usuarios.findUser(SG.user).getImageList().getSize();
        if(size>0){
            for (int i = 0; i < size; i++) {
                cboImage.addItem("Imagen "+Data.SG.lista_usuarios.findUser(SG.user).getImageList().get(i+1).getId());
            }
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategory = new javax.swing.JList<>();
        selectedImage = new javax.swing.JLabel();
        cmdAddImage = new javaswing.controls.ButtonCustom();
        cmdDeleteImage = new javaswing.controls.ButtonCustom();
        cboImage = new javaswing.controls.Combobox();
        cmdAddCategory = new javaswing.controls.ButtonCustom();
        cmdDeleteCategory = new javaswing.controls.ButtonCustom();
        cmdAddImage2 = new javaswing.controls.ButtonCustom();
        cmdAddImage3 = new javaswing.controls.ButtonCustom();
        cmdMenu = new javaswing.controls.ButtonCustom();
        lblUser = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Categorias");

        lstCategory.setBackground(new java.awt.Color(255, 255, 255));
        lstCategory.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "General" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstCategory);

        cmdAddImage.setText("Agregar Imagen");
        cmdAddImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddImageActionPerformed(evt);
            }
        });

        cmdDeleteImage.setText("Eliminar Imagen");
        cmdDeleteImage.setStyle(javaswing.controls.ButtonCustom.ButtonStyle.DESTRUCTIVE);
        cmdDeleteImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteImageActionPerformed(evt);
            }
        });

        cboImage.setLabeText("Seleccionar Imagen");
        cboImage.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboImageItemStateChanged(evt);
            }
        });

        cmdAddCategory.setText("Agregar Categoria");
        cmdAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddCategoryActionPerformed(evt);
            }
        });

        cmdDeleteCategory.setText("Eliminar Categoria");
        cmdDeleteCategory.setStyle(javaswing.controls.ButtonCustom.ButtonStyle.DESTRUCTIVE);
        cmdDeleteCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteCategoryActionPerformed(evt);
            }
        });

        cmdAddImage2.setText("Siguiente");
        cmdAddImage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddImage2ActionPerformed(evt);
            }
        });

        cmdAddImage3.setText("Anterior");
        cmdAddImage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddImage3ActionPerformed(evt);
            }
        });

        cmdMenu.setText("Menu");
        cmdMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMenuActionPerformed(evt);
            }
        });

        lblUser.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cmdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(cboImage, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(cmdAddImage, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdDeleteImage, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmdAddImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectedImage, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdDeleteCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmdAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmdAddImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lblUser)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmdAddImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdDeleteImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUser)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selectedImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdAddImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdAddImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdDeleteCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        menu.setTitle("Menu");
    }//GEN-LAST:event_cmdMenuActionPerformed

    private void cmdAddImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddImageActionPerformed
        // TODO add your handling code here:
        JFileChooser escojerImagen = new JFileChooser();
        
        int eleccion = escojerImagen.showOpenDialog(this);
        
        if(eleccion == JFileChooser.APPROVE_OPTION) {
            fichero = escojerImagen.getSelectedFile();
            
            ImageIcon imagen = new ImageIcon(fichero.getPath());
            
            Icon icono = new ImageIcon(imagen.getImage().
                           getScaledInstance(selectedImage.getWidth(), selectedImage.getHeight(), java.awt.Image.SCALE_DEFAULT));
            
            selectedImage.setIcon(icono);
         
            ImagePathList.Lista listaImage = new ImagePathList.Lista();
        

        ImagePathList.Image newImage = new Image();
        newImage.setId(Data.SG.lista_usuarios.findUser(Data.SG.user).getImageList().getSize()+1);
        newImage.setPath(fichero.getPath());
        newImage.setCategory("General");
        Data.SG.lista_usuarios.findUser(Data.SG.user).getImageList().add(newImage);
        cboImage.addItem("Imagen "+newImage.getId());
        
        Data.DataUsers.createData();
        }else{
            System.out.println("Imagen no seleccionada");
        }
        
        
    }//GEN-LAST:event_cmdAddImageActionPerformed

    private void cmdAddImage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddImage2ActionPerformed
        // TODO add your handling code here:
        
        if(nImage<Data.SG.lista_usuarios.findUser(Data.SG.user).getImageList().getSize()){
            nImage=nImage+1;
            System.out.println("Niamge "+ nImage);
            mostrarImagen(nImage);
        DefaultListModel<String> listModel = new DefaultListModel<>();
        listModel.clear();
        lstCategory.setModel(listModel);
        listModel.addElement(Data.SG.lista_usuarios.findUser(Data.SG.user).getImageList().get(nImage).getCategory());
        }
        
    }//GEN-LAST:event_cmdAddImage2ActionPerformed

    private void cmdAddImage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddImage3ActionPerformed
        // TODO add your handling code here:
        
        if(nImage<=Data.SG.lista_usuarios.findUser(Data.SG.user).getImageList().getSize() && nImage>0){
            nImage=nImage-1;
            System.out.println("Niamge "+ nImage);
            mostrarImagen(nImage);
            DefaultListModel<String> listModel = new DefaultListModel<>();
        listModel.clear();
        lstCategory.setModel(listModel);
        listModel.addElement(Data.SG.lista_usuarios.findUser(Data.SG.user).getImageList().get(nImage).getCategory());
        }
        
    }//GEN-LAST:event_cmdAddImage3ActionPerformed

    private void cboImageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboImageItemStateChanged
        // TODO add your handling code here:            
            ImageIcon imagen = new ImageIcon(Data.SG.lista_usuarios.findUser(Data.SG.user).getImageList().get((cboImage.getSelectedIndex()+1)).getPath());
            
            Icon icono = new ImageIcon(imagen.getImage().
                           getScaledInstance(selectedImage.getWidth(), selectedImage.getHeight(), java.awt.Image.SCALE_DEFAULT));
            
            selectedImage.setIcon(icono);
            
            nImage= cboImage.getSelectedIndex()+1;
            DefaultListModel<String> listModel = new DefaultListModel<>();
        listModel.clear();
        lstCategory.setModel(listModel);
        listModel.addElement(Data.SG.lista_usuarios.findUser(Data.SG.user).getImageList().get(nImage).getCategory());
    }//GEN-LAST:event_cboImageItemStateChanged

    private void cmdDeleteImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteImageActionPerformed
        // TODO add your handling code here:
        try {
            Data.SG.lista_usuarios.findUser(Data.SG.user).getImageList().deleteImage(nImage);    
            System.out.println("Borardo correctamente");
            DataUsers.createData();
        } catch (Exception e) {
            System.out.println("No se pudo borrar");
        }
        cboImage.remove(cboImage.getSelectedIndex());
        
        DefaultListModel<String> listModel = new DefaultListModel<>();
        listModel.clear();
        lstCategory.setModel(listModel);
        listModel.addElement(Data.SG.lista_usuarios.findUser(Data.SG.user).getImageList().get(nImage).getCategory());
    }//GEN-LAST:event_cmdDeleteImageActionPerformed

    private void cmdAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddCategoryActionPerformed
        // TODO add your handling code here:
        String newCategory= JOptionPane.showInputDialog("Ingrese le categoria");
        Data.SG.lista_usuarios.findUser(Data.SG.user).getImageList().get(nImage).setCategory(newCategory);
        
        
        DefaultListModel<String> listModel = new DefaultListModel<>();
        listModel.clear();
        lstCategory.setModel(listModel);
        listModel.addElement(Data.SG.lista_usuarios.findUser(Data.SG.user).getImageList().get(nImage).getCategory());
        DataUsers.createData();
    }//GEN-LAST:event_cmdAddCategoryActionPerformed

    private void cmdDeleteCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteCategoryActionPerformed
        // TODO add your handling code here:
        String newCategory= JOptionPane.showInputDialog("Ingrese le categoria");
        Data.SG.lista_usuarios.findUser(Data.SG.user).getImageList().get(nImage).setCategory("General");
        
        
        DefaultListModel<String> listModel = new DefaultListModel<>();
        listModel.clear();
        lstCategory.setModel(listModel);
        listModel.addElement(Data.SG.lista_usuarios.findUser(Data.SG.user).getImageList().get(nImage).getCategory());
        DataUsers.createData();
    }//GEN-LAST:event_cmdDeleteCategoryActionPerformed
    int nImage=0;
    public void mostrarImagen(int i){
            
            ImageIcon imagen = new ImageIcon(Data.SG.lista_usuarios.findUser(Data.SG.user).getImageList().get(i).getPath());
            
            Icon icono = new ImageIcon(imagen.getImage().
                           getScaledInstance(selectedImage.getWidth(), selectedImage.getHeight(), java.awt.Image.SCALE_DEFAULT));
            
            selectedImage.setIcon(icono);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaswing.controls.Combobox cboImage;
    private javaswing.controls.ButtonCustom cmdAddCategory;
    private javaswing.controls.ButtonCustom cmdAddImage;
    private javaswing.controls.ButtonCustom cmdAddImage2;
    private javaswing.controls.ButtonCustom cmdAddImage3;
    private javaswing.controls.ButtonCustom cmdDeleteCategory;
    private javaswing.controls.ButtonCustom cmdDeleteImage;
    private javaswing.controls.ButtonCustom cmdMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JList<String> lstCategory;
    private javax.swing.JLabel selectedImage;
    // End of variables declaration//GEN-END:variables
}
