/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import ImagePathList.Image;
import UserList.User;
import java.awt.Color;
import javaswing.controls.ButtonCustom;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author bruce
 */
public class Convertidor extends javax.swing.JFrame {

    /**
     * Creates new form Convertidor
     */
    int option = 0;

    public Convertidor() {
        initComponents();
        initialData();
    }

    public void initialData() {
        for (int i = 0; i < Data.SG.lista_usuarios.getSize(); i++) {
            cboUser.addItem(Data.SG.lista_usuarios.getUserIndex(i).getUser());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboUser = new javaswing.controls.Combobox();
        cboCategory = new javaswing.controls.Combobox();
        cmdAdd = new javaswing.controls.ButtonCustom();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCola = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        cmdJPEGaBMP = new javaswing.controls.ButtonCustom();
        cmdCopyJPEG = new javaswing.controls.ButtonCustom();
        cmdRGB = new javaswing.controls.ButtonCustom();
        cmdModifyImage = new javaswing.controls.ButtonCustom();
        cmdWhiteBlack = new javaswing.controls.ButtonCustom();
        cmdExecute = new javaswing.controls.ButtonCustom();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConsole = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        cmdMenu = new javaswing.controls.ButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cboUser.setLabeText("Usuario");
        cboUser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboUserItemStateChanged(evt);
            }
        });

        cboCategory.setLabeText("Categoria");

        cmdAdd.setText("Agregar");
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });

        lstCola.setBackground(new java.awt.Color(255, 255, 255));
        lstCola.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstCola);

        jLabel1.setText("Cola de procesamiento");

        cmdJPEGaBMP.setText("JPEG a BMP y Vieversa");
        cmdJPEGaBMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdJPEGaBMPActionPerformed(evt);
            }
        });

        cmdCopyJPEG.setText("Copia JPEG");
        cmdCopyJPEG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCopyJPEGActionPerformed(evt);
            }
        });

        cmdRGB.setText("Rojo, verde, Azul, Spehia");
        cmdRGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRGBActionPerformed(evt);
            }
        });

        cmdModifyImage.setText("Modificar Imagen");
        cmdModifyImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModifyImageActionPerformed(evt);
            }
        });

        cmdWhiteBlack.setText("Blanco y negro");
        cmdWhiteBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdWhiteBlackActionPerformed(evt);
            }
        });

        cmdExecute.setText("Ejecutar en paralelo");
        cmdExecute.setStyle(javaswing.controls.ButtonCustom.ButtonStyle.DESTRUCTIVE);
        cmdExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExecuteActionPerformed(evt);
            }
        });

        txtConsole.setBackground(new java.awt.Color(255, 255, 255));
        txtConsole.setColumns(20);
        txtConsole.setRows(5);
        jScrollPane2.setViewportView(txtConsole);

        jLabel2.setText("Consola de ejecucion");

        cmdMenu.setText("Menu");
        cmdMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmdJPEGaBMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmdCopyJPEG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmdRGB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmdModifyImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmdWhiteBlack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(55, 55, 55)
                                        .addComponent(cmdExecute, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cboUser, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdJPEGaBMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdExecute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdCopyJPEG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdRGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdModifyImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdWhiteBlack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboUserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboUserItemStateChanged
        // TODO add your handling code here:

        ImagePathList.Lista listImage = Data.SG.lista_usuarios.getUserIndex(cboUser.getSelectedIndex()).getImageList();

        cboCategory.removeAllItems();

        for (int j = 0; j < listImage.getSize(); j++) {
            String categoria = listImage.getCategoryIndex(j).getCategory();

            // Verificar si la categoría ya fue agregada al ComboBox
            boolean categoriaAgregada = false;
            for (int k = 0; k < cboCategory.getItemCount(); k++) {
                if (cboCategory.getItemAt(k).equals(categoria)) {
                    categoriaAgregada = true;
                    break;
                }
            }

            // Si la categoría no ha sido agregada, la agregamos al ComboBox
            if (!categoriaAgregada) {
                cboCategory.addItem(categoria);
            }
        }
    }//GEN-LAST:event_cboUserItemStateChanged

    private void cmdMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        menu.setTitle("Menu");
    }//GEN-LAST:event_cmdMenuActionPerformed

    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
        // TODO add your handling code here:
        ImagePathList.Lista listImage = Data.SG.lista_usuarios.getUserIndex(cboUser.getSelectedIndex()).getImageList();
        listImage.addListCategoriesUser((String) cboCategory.getSelectedItem());
        showProcess();
    }//GEN-LAST:event_cmdAddActionPerformed

    private void cmdExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExecuteActionPerformed
        // TODO add your handling code here:
        switch (option) {
            case 1:

                break;
            case 2:

                break;
            case 3:

                break;
            case 4:

                break;
            case 5:

                break;
            default:
                JOptionPane.showMessageDialog(null, "No ha seleccioando una opcion");
                throw new AssertionError();
        }
    }//GEN-LAST:event_cmdExecuteActionPerformed

    private void cmdJPEGaBMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdJPEGaBMPActionPerformed
        // TODO add your handling code here:
        option = 1;
        clearColors();
        cmdJPEGaBMP.setStyle(ButtonCustom.ButtonStyle.DESTRUCTIVE);
    }//GEN-LAST:event_cmdJPEGaBMPActionPerformed

    private void cmdCopyJPEGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCopyJPEGActionPerformed
        // TODO add your handling code here:
        option = 2;
        clearColors();
        cmdCopyJPEG.setStyle(ButtonCustom.ButtonStyle.DESTRUCTIVE);
    }//GEN-LAST:event_cmdCopyJPEGActionPerformed

    private void cmdRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRGBActionPerformed
        // TODO add your handling code here:
        option = 3;
        clearColors();
        cmdRGB.setStyle(ButtonCustom.ButtonStyle.DESTRUCTIVE);
    }//GEN-LAST:event_cmdRGBActionPerformed

    private void cmdModifyImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModifyImageActionPerformed
        // TODO add your handling code here:
        option = 4;
        clearColors();
        cmdModifyImage.setStyle(ButtonCustom.ButtonStyle.DESTRUCTIVE);
    }//GEN-LAST:event_cmdModifyImageActionPerformed

    private void cmdWhiteBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdWhiteBlackActionPerformed
        // TODO add your handling code here:
        option = 5;
        clearColors();
        cmdWhiteBlack.setStyle(ButtonCustom.ButtonStyle.DESTRUCTIVE);
    }//GEN-LAST:event_cmdWhiteBlackActionPerformed

    public void clearColors() {
        cmdJPEGaBMP.setStyle(ButtonCustom.ButtonStyle.PRIMARY);
        cmdModifyImage.setStyle(ButtonCustom.ButtonStyle.PRIMARY);
        cmdRGB.setStyle(ButtonCustom.ButtonStyle.PRIMARY);
        cmdWhiteBlack.setStyle(ButtonCustom.ButtonStyle.PRIMARY);
        cmdCopyJPEG.setStyle(ButtonCustom.ButtonStyle.PRIMARY);
    }

    public void showProcess() {
        DefaultListModel<String> listModel = new DefaultListModel<>();
        listModel.clear();
        lstCola.setModel(listModel);

        for (int i = 0; i < Data.SG.listImageWorks.getSize(); i++) {
            listModel.addElement(Data.SG.listImageWorks.getListImage(i).getPath());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaswing.controls.Combobox cboCategory;
    private javaswing.controls.Combobox cboUser;
    private javaswing.controls.ButtonCustom cmdAdd;
    private javaswing.controls.ButtonCustom cmdCopyJPEG;
    private javaswing.controls.ButtonCustom cmdExecute;
    private javaswing.controls.ButtonCustom cmdJPEGaBMP;
    private javaswing.controls.ButtonCustom cmdMenu;
    private javaswing.controls.ButtonCustom cmdModifyImage;
    private javaswing.controls.ButtonCustom cmdRGB;
    private javaswing.controls.ButtonCustom cmdWhiteBlack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstCola;
    private javax.swing.JTextArea txtConsole;
    // End of variables declaration//GEN-END:variables
}
